/*****************************************************************************************************
* FileName:                    Setting.c
*
* Description:                 定值文件
*
* Author:                      YanDengxue, Fiberhome-Fuhua
*
* Rev History:
*       <Author>        <Data>        <Hardware>     <Version>        <Description>
*     YanDengxue   2011-03-29 15:30       --           1.00             Create
*****************************************************************************************************/
//====================================================================================================
// 本文件使用的头文件
//====================================================================================================
// 自定义头文件
#include "STM32F40xRegister.h"
#include "SystemBase.h"
#include "Setting.h"
#include "Uart.h"
#include "UserApp.h"

//====================================================================================================
// 本文件定义的与外部的接口变量
//====================================================================================================
SIGNAL_DEFINE const setting_system_define[] =
{
    {"uart2_comm_protocol",             &uart2.comm_protocol,                 SIGNAL_DATA_TYPE_uc},
    {"uart2_comm_addr",                 &uart2.comm_addr,                     SIGNAL_DATA_TYPE_ui},
    {"uart2_baud_rate",                 &uart2.baud_rate,                     SIGNAL_DATA_TYPE_uc},
    {"uart2_parity",                    &uart2.parity,                        SIGNAL_DATA_TYPE_uc},
    {"uart2_stop_bits",                 &uart2.stop_bits,                     SIGNAL_DATA_TYPE_uc},
    {"uart2_rx_timeout_ms",             &uart2.rx_timeout_ms,                 SIGNAL_DATA_TYPE_ul},
    {"uart2_comm_mode",                 &uart2.comm_mode,                     SIGNAL_DATA_TYPE_uc},

    {"uart4_comm_protocol",             &uart4.comm_protocol,                 SIGNAL_DATA_TYPE_uc},
    {"uart4_comm_addr",                 &uart4.comm_addr,                     SIGNAL_DATA_TYPE_ui},
    {"uart4_baud_rate",                 &uart4.baud_rate,                     SIGNAL_DATA_TYPE_uc},
    {"uart4_parity",                    &uart4.parity,                        SIGNAL_DATA_TYPE_uc},
    {"uart4_stop_bits",                 &uart4.stop_bits,                     SIGNAL_DATA_TYPE_uc},
    {"uart4_rx_timeout_ms",             &uart4.rx_timeout_ms,                 SIGNAL_DATA_TYPE_ul},
    {"uart4_comm_mode",                 &uart4.comm_mode,                     SIGNAL_DATA_TYPE_uc},

    {"measure_delay",                   &measure_delay,                       SIGNAL_DATA_TYPE_ul},
    {"use_freq_amp_calc_T",             &saw_temperature_use_freq_amp,        SIGNAL_DATA_TYPE_c},
    {"fft_amp_filter_enable",           &fft_amp_filter_enable,               SIGNAL_DATA_TYPE_c},
    {"saw_auto_tx_attenuator_min",      &saw_auto_tx_attenuator_min,          SIGNAL_DATA_TYPE_uc},

    {"device_offline",                  &device_offline,                      SIGNAL_DATA_TYPE_c},

    {"antenna0_offline",                &antenna[0].offline,                 SIGNAL_DATA_TYPE_uc},
    {"antenna1_offline",                &antenna[1].offline,                 SIGNAL_DATA_TYPE_uc},
    {"antenna2_offline",                &antenna[2].offline,                 SIGNAL_DATA_TYPE_uc},
    {"antenna3_offline",                &antenna[3].offline,                 SIGNAL_DATA_TYPE_uc},
    {"antenna4_offline",                &antenna[4].offline,                 SIGNAL_DATA_TYPE_uc},
    {"antenna5_offline",                &antenna[5].offline,                 SIGNAL_DATA_TYPE_uc},

    {"antenna0_saw_delay_from_tx",               &antenna[0].delay_time_from_tx_to_rx,                           SIGNAL_DATA_TYPE_ui},
    {"antenna0_saw_send_hold_time",              &antenna[0].send_hold_time,                                     SIGNAL_DATA_TYPE_ul},
    {"antenna0_sensor0_offline",                 &antenna[0].temperature_sensor[0].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor0_calibrate_T",             &antenna[0].temperature_sensor[0].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna0_sensor0_rtx_power_autoadjust",    &antenna[0].temperature_sensor[0].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna0_sensor0_tx_attenuator",           &antenna[0].temperature_sensor[0].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor0_rx_attenuator"    ,       &antenna[0].temperature_sensor[0].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor0_start_freq_tab_index",    &antenna[0].temperature_sensor[0].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor0_end_freq_tab_index",      &antenna[0].temperature_sensor[0].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor0_slope_T",                 &antenna[0].temperature_sensor[0].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna0_sensor1_offline",                 &antenna[0].temperature_sensor[1].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor1_calibrate_T",             &antenna[0].temperature_sensor[1].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna0_sensor1_rtx_power_autoadjust",    &antenna[0].temperature_sensor[1].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna0_sensor1_tx_attenuator",           &antenna[0].temperature_sensor[1].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor1_rx_attenuator"    ,       &antenna[0].temperature_sensor[1].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor1_start_freq_tab_index",    &antenna[0].temperature_sensor[1].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor1_end_freq_tab_index",      &antenna[0].temperature_sensor[1].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor1_slope_T",                 &antenna[0].temperature_sensor[1].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna0_sensor2_offline",                 &antenna[0].temperature_sensor[2].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor2_calibrate_T",             &antenna[0].temperature_sensor[2].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna0_sensor2_rtx_power_autoadjust",    &antenna[0].temperature_sensor[2].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna0_sensor2_tx_attenuator",           &antenna[0].temperature_sensor[2].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor2_rx_attenuator"    ,       &antenna[0].temperature_sensor[2].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor2_start_freq_tab_index",    &antenna[0].temperature_sensor[2].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor2_end_freq_tab_index",      &antenna[0].temperature_sensor[2].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor2_slope_T",                 &antenna[0].temperature_sensor[2].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna0_sensor3_offline",                 &antenna[0].temperature_sensor[3].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor3_calibrate_T",             &antenna[0].temperature_sensor[3].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna0_sensor3_rtx_power_autoadjust",    &antenna[0].temperature_sensor[3].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna0_sensor3_tx_attenuator",           &antenna[0].temperature_sensor[3].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor3_rx_attenuator"    ,       &antenna[0].temperature_sensor[3].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor3_start_freq_tab_index",    &antenna[0].temperature_sensor[3].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor3_end_freq_tab_index",      &antenna[0].temperature_sensor[3].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor3_slope_T",                 &antenna[0].temperature_sensor[3].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna0_sensor4_offline",                 &antenna[0].temperature_sensor[4].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor4_calibrate_T",             &antenna[0].temperature_sensor[4].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna0_sensor4_rtx_power_autoadjust",    &antenna[0].temperature_sensor[4].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna0_sensor4_tx_attenuator",           &antenna[0].temperature_sensor[4].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor4_rx_attenuator"    ,       &antenna[0].temperature_sensor[4].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor4_start_freq_tab_index",    &antenna[0].temperature_sensor[4].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor4_end_freq_tab_index",      &antenna[0].temperature_sensor[4].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor4_slope_T",                 &antenna[0].temperature_sensor[4].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna0_sensor5_offline",                 &antenna[0].temperature_sensor[5].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor5_calibrate_T",             &antenna[0].temperature_sensor[5].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna0_sensor5_rtx_power_autoadjust",    &antenna[0].temperature_sensor[5].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna0_sensor5_tx_attenuator",           &antenna[0].temperature_sensor[5].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor5_rx_attenuator"    ,       &antenna[0].temperature_sensor[5].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna0_sensor5_start_freq_tab_index",    &antenna[0].temperature_sensor[5].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor5_end_freq_tab_index",      &antenna[0].temperature_sensor[5].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna0_sensor5_slope_T",                 &antenna[0].temperature_sensor[5].measure_slope,                SIGNAL_DATA_TYPE_l},

    {"antenna1_saw_delay_from_tx",               &antenna[1].delay_time_from_tx_to_rx,                           SIGNAL_DATA_TYPE_ui},
    {"antenna1_saw_send_hold_time",              &antenna[1].send_hold_time,                                     SIGNAL_DATA_TYPE_ul},
    {"antenna1_sensor0_offline",                 &antenna[1].temperature_sensor[0].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor0_calibrate_T",             &antenna[1].temperature_sensor[0].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna1_sensor0_rtx_power_autoadjust",    &antenna[1].temperature_sensor[0].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna1_sensor0_tx_attenuator",           &antenna[1].temperature_sensor[0].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor0_rx_attenuator"    ,       &antenna[1].temperature_sensor[0].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor0_start_freq_tab_index",    &antenna[1].temperature_sensor[0].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor0_end_freq_tab_index",      &antenna[1].temperature_sensor[0].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor0_slope_T",                 &antenna[1].temperature_sensor[0].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna1_sensor1_offline",                 &antenna[1].temperature_sensor[1].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor1_calibrate_T",             &antenna[1].temperature_sensor[1].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna1_sensor1_rtx_power_autoadjust",    &antenna[1].temperature_sensor[1].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna1_sensor1_tx_attenuator",           &antenna[1].temperature_sensor[1].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor1_rx_attenuator"    ,       &antenna[1].temperature_sensor[1].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor1_start_freq_tab_index",    &antenna[1].temperature_sensor[1].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor1_end_freq_tab_index",      &antenna[1].temperature_sensor[1].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor1_slope_T",                 &antenna[1].temperature_sensor[1].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna1_sensor2_offline",                 &antenna[1].temperature_sensor[2].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor2_calibrate_T",             &antenna[1].temperature_sensor[2].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna1_sensor2_rtx_power_autoadjust",    &antenna[1].temperature_sensor[2].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna1_sensor2_tx_attenuator",           &antenna[1].temperature_sensor[2].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor2_rx_attenuator"    ,       &antenna[1].temperature_sensor[2].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor2_start_freq_tab_index",    &antenna[1].temperature_sensor[2].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor2_end_freq_tab_index",      &antenna[1].temperature_sensor[2].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor2_slope_T",                 &antenna[1].temperature_sensor[2].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna1_sensor3_offline",                 &antenna[1].temperature_sensor[3].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor3_calibrate_T",             &antenna[1].temperature_sensor[3].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna1_sensor3_rtx_power_autoadjust",    &antenna[1].temperature_sensor[3].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna1_sensor3_tx_attenuator",           &antenna[1].temperature_sensor[3].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor3_rx_attenuator"    ,       &antenna[1].temperature_sensor[3].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor3_start_freq_tab_index",    &antenna[1].temperature_sensor[3].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor3_end_freq_tab_index",      &antenna[1].temperature_sensor[3].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor3_slope_T",                 &antenna[1].temperature_sensor[3].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna1_sensor4_offline",                 &antenna[1].temperature_sensor[4].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor4_calibrate_T",             &antenna[1].temperature_sensor[4].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna1_sensor4_rtx_power_autoadjust",    &antenna[1].temperature_sensor[4].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna1_sensor4_tx_attenuator",           &antenna[1].temperature_sensor[4].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor4_rx_attenuator"    ,       &antenna[1].temperature_sensor[4].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor4_start_freq_tab_index",    &antenna[1].temperature_sensor[4].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor4_end_freq_tab_index",      &antenna[1].temperature_sensor[4].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor4_slope_T",                 &antenna[1].temperature_sensor[4].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna1_sensor5_offline",                 &antenna[1].temperature_sensor[5].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor5_calibrate_T",             &antenna[1].temperature_sensor[5].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna1_sensor5_rtx_power_autoadjust",    &antenna[1].temperature_sensor[5].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna1_sensor5_tx_attenuator",           &antenna[1].temperature_sensor[5].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor5_rx_attenuator"    ,       &antenna[1].temperature_sensor[5].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna1_sensor5_start_freq_tab_index",    &antenna[1].temperature_sensor[5].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor5_end_freq_tab_index",      &antenna[1].temperature_sensor[5].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna1_sensor5_slope_T",                 &antenna[1].temperature_sensor[5].measure_slope,                SIGNAL_DATA_TYPE_l},

    {"antenna2_saw_delay_from_tx",               &antenna[2].delay_time_from_tx_to_rx,                           SIGNAL_DATA_TYPE_ui},
    {"antenna2_saw_send_hold_time",              &antenna[2].send_hold_time,                                     SIGNAL_DATA_TYPE_ul},
    {"antenna2_sensor0_offline",                 &antenna[2].temperature_sensor[0].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor0_calibrate_T",             &antenna[2].temperature_sensor[0].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna2_sensor0_rtx_power_autoadjust",    &antenna[2].temperature_sensor[0].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna2_sensor0_tx_attenuator",           &antenna[2].temperature_sensor[0].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor0_rx_attenuator"    ,       &antenna[2].temperature_sensor[0].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor0_start_freq_tab_index",    &antenna[2].temperature_sensor[0].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor0_end_freq_tab_index",      &antenna[2].temperature_sensor[0].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor0_slope_T",                 &antenna[2].temperature_sensor[0].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna2_sensor1_offline",                 &antenna[2].temperature_sensor[1].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor1_calibrate_T",             &antenna[2].temperature_sensor[1].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna2_sensor1_rtx_power_autoadjust",    &antenna[2].temperature_sensor[1].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna2_sensor1_tx_attenuator",           &antenna[2].temperature_sensor[1].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor1_rx_attenuator"    ,       &antenna[2].temperature_sensor[1].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor1_start_freq_tab_index",    &antenna[2].temperature_sensor[1].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor1_end_freq_tab_index",      &antenna[2].temperature_sensor[1].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor1_slope_T",                 &antenna[2].temperature_sensor[1].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna2_sensor2_offline",                 &antenna[2].temperature_sensor[2].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor2_calibrate_T",             &antenna[2].temperature_sensor[2].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna2_sensor2_rtx_power_autoadjust",    &antenna[2].temperature_sensor[2].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna2_sensor2_tx_attenuator",           &antenna[2].temperature_sensor[2].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor2_rx_attenuator"    ,       &antenna[2].temperature_sensor[2].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor2_start_freq_tab_index",    &antenna[2].temperature_sensor[2].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor2_end_freq_tab_index",      &antenna[2].temperature_sensor[2].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor2_slope_T",                 &antenna[2].temperature_sensor[2].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna2_sensor3_offline",                 &antenna[2].temperature_sensor[3].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor3_calibrate_T",             &antenna[2].temperature_sensor[3].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna2_sensor3_rtx_power_autoadjust",    &antenna[2].temperature_sensor[3].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna2_sensor3_tx_attenuator",           &antenna[2].temperature_sensor[3].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor3_rx_attenuator"    ,       &antenna[2].temperature_sensor[3].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor3_start_freq_tab_index",    &antenna[2].temperature_sensor[3].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor3_end_freq_tab_index",      &antenna[2].temperature_sensor[3].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor3_slope_T",                 &antenna[2].temperature_sensor[3].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna2_sensor4_offline",                 &antenna[2].temperature_sensor[4].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor4_calibrate_T",             &antenna[2].temperature_sensor[4].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna2_sensor4_rtx_power_autoadjust",    &antenna[2].temperature_sensor[4].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna2_sensor4_tx_attenuator",           &antenna[2].temperature_sensor[4].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor4_rx_attenuator"    ,       &antenna[2].temperature_sensor[4].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor4_start_freq_tab_index",    &antenna[2].temperature_sensor[4].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor4_end_freq_tab_index",      &antenna[2].temperature_sensor[4].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor4_slope_T",                 &antenna[2].temperature_sensor[4].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna2_sensor5_offline",                 &antenna[2].temperature_sensor[5].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor5_calibrate_T",             &antenna[2].temperature_sensor[5].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna2_sensor5_rtx_power_autoadjust",    &antenna[2].temperature_sensor[5].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna2_sensor5_tx_attenuator",           &antenna[2].temperature_sensor[5].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor5_rx_attenuator"    ,       &antenna[2].temperature_sensor[5].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna2_sensor5_start_freq_tab_index",    &antenna[2].temperature_sensor[5].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor5_end_freq_tab_index",      &antenna[2].temperature_sensor[5].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna2_sensor5_slope_T",                 &antenna[2].temperature_sensor[5].measure_slope,                SIGNAL_DATA_TYPE_l},

    {"antenna3_saw_delay_from_tx",               &antenna[3].delay_time_from_tx_to_rx,                           SIGNAL_DATA_TYPE_ui},
    {"antenna3_saw_send_hold_time",              &antenna[3].send_hold_time,                                     SIGNAL_DATA_TYPE_ul},
    {"antenna3_sensor0_offline",                 &antenna[3].temperature_sensor[0].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor0_calibrate_T",             &antenna[3].temperature_sensor[0].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna3_sensor0_rtx_power_autoadjust",    &antenna[3].temperature_sensor[0].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna3_sensor0_tx_attenuator",           &antenna[3].temperature_sensor[0].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor0_rx_attenuator"    ,       &antenna[3].temperature_sensor[0].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor0_start_freq_tab_index",    &antenna[3].temperature_sensor[0].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor0_end_freq_tab_index",      &antenna[3].temperature_sensor[0].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor0_slope_T",                 &antenna[3].temperature_sensor[0].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna3_sensor1_offline",                 &antenna[3].temperature_sensor[1].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor1_calibrate_T",             &antenna[3].temperature_sensor[1].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna3_sensor1_rtx_power_autoadjust",    &antenna[3].temperature_sensor[1].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna3_sensor1_tx_attenuator",           &antenna[3].temperature_sensor[1].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor1_rx_attenuator"    ,       &antenna[3].temperature_sensor[1].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor1_start_freq_tab_index",    &antenna[3].temperature_sensor[1].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor1_end_freq_tab_index",      &antenna[3].temperature_sensor[1].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor1_slope_T",                 &antenna[3].temperature_sensor[1].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna3_sensor2_offline",                 &antenna[3].temperature_sensor[2].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor2_calibrate_T",             &antenna[3].temperature_sensor[2].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna3_sensor2_rtx_power_autoadjust",    &antenna[3].temperature_sensor[2].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna3_sensor2_tx_attenuator",           &antenna[3].temperature_sensor[2].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor2_rx_attenuator"    ,       &antenna[3].temperature_sensor[2].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor2_start_freq_tab_index",    &antenna[3].temperature_sensor[2].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor2_end_freq_tab_index",      &antenna[3].temperature_sensor[2].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor2_slope_T",                 &antenna[3].temperature_sensor[2].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna3_sensor3_offline",                 &antenna[3].temperature_sensor[3].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor3_calibrate_T",             &antenna[3].temperature_sensor[3].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna3_sensor3_rtx_power_autoadjust",    &antenna[3].temperature_sensor[3].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna3_sensor3_tx_attenuator",           &antenna[3].temperature_sensor[3].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor3_rx_attenuator"    ,       &antenna[3].temperature_sensor[3].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor3_start_freq_tab_index",    &antenna[3].temperature_sensor[3].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor3_end_freq_tab_index",      &antenna[3].temperature_sensor[3].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor3_slope_T",                 &antenna[3].temperature_sensor[3].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna3_sensor4_offline",                 &antenna[3].temperature_sensor[4].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor4_calibrate_T",             &antenna[3].temperature_sensor[4].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna3_sensor4_rtx_power_autoadjust",    &antenna[3].temperature_sensor[4].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna3_sensor4_tx_attenuator",           &antenna[3].temperature_sensor[4].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor4_rx_attenuator"    ,       &antenna[3].temperature_sensor[4].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor4_start_freq_tab_index",    &antenna[3].temperature_sensor[4].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor4_end_freq_tab_index",      &antenna[3].temperature_sensor[4].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor4_slope_T",                 &antenna[3].temperature_sensor[4].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna3_sensor5_offline",                 &antenna[3].temperature_sensor[5].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor5_calibrate_T",             &antenna[3].temperature_sensor[5].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna3_sensor5_rtx_power_autoadjust",    &antenna[3].temperature_sensor[5].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna3_sensor5_tx_attenuator",           &antenna[3].temperature_sensor[5].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor5_rx_attenuator"    ,       &antenna[3].temperature_sensor[5].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna3_sensor5_start_freq_tab_index",    &antenna[3].temperature_sensor[5].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor5_end_freq_tab_index",      &antenna[3].temperature_sensor[5].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna3_sensor5_slope_T",                 &antenna[3].temperature_sensor[5].measure_slope,                SIGNAL_DATA_TYPE_l},

    {"antenna4_saw_delay_from_tx",               &antenna[4].delay_time_from_tx_to_rx,                           SIGNAL_DATA_TYPE_ui},
    {"antenna4_saw_send_hold_time",              &antenna[4].send_hold_time,                                     SIGNAL_DATA_TYPE_ul},
    {"antenna4_sensor0_offline",                 &antenna[4].temperature_sensor[0].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor0_calibrate_T",             &antenna[4].temperature_sensor[0].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna4_sensor0_rtx_power_autoadjust",    &antenna[4].temperature_sensor[0].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna4_sensor0_tx_attenuator",           &antenna[4].temperature_sensor[0].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor0_rx_attenuator"    ,       &antenna[4].temperature_sensor[0].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor0_start_freq_tab_index",    &antenna[4].temperature_sensor[0].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor0_end_freq_tab_index",      &antenna[4].temperature_sensor[0].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor0_slope_T",                 &antenna[4].temperature_sensor[0].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna4_sensor1_offline",                 &antenna[4].temperature_sensor[1].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor1_calibrate_T",             &antenna[4].temperature_sensor[1].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna4_sensor1_rtx_power_autoadjust",    &antenna[4].temperature_sensor[1].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna4_sensor1_tx_attenuator",           &antenna[4].temperature_sensor[1].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor1_rx_attenuator"    ,       &antenna[4].temperature_sensor[1].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor1_start_freq_tab_index",    &antenna[4].temperature_sensor[1].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor1_end_freq_tab_index",      &antenna[4].temperature_sensor[1].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor1_slope_T",                 &antenna[4].temperature_sensor[1].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna4_sensor2_offline",                 &antenna[4].temperature_sensor[2].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor2_calibrate_T",             &antenna[4].temperature_sensor[2].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna4_sensor2_rtx_power_autoadjust",    &antenna[4].temperature_sensor[2].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna4_sensor2_tx_attenuator",           &antenna[4].temperature_sensor[2].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor2_rx_attenuator"    ,       &antenna[4].temperature_sensor[2].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor2_start_freq_tab_index",    &antenna[4].temperature_sensor[2].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor2_end_freq_tab_index",      &antenna[4].temperature_sensor[2].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor2_slope_T",                 &antenna[4].temperature_sensor[2].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna4_sensor3_offline",                 &antenna[4].temperature_sensor[3].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor3_calibrate_T",             &antenna[4].temperature_sensor[3].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna4_sensor3_rtx_power_autoadjust",    &antenna[4].temperature_sensor[3].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna4_sensor3_tx_attenuator",           &antenna[4].temperature_sensor[3].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor3_rx_attenuator"    ,       &antenna[4].temperature_sensor[3].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor3_start_freq_tab_index",    &antenna[4].temperature_sensor[3].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor3_end_freq_tab_index",      &antenna[4].temperature_sensor[3].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor3_slope_T",                 &antenna[4].temperature_sensor[3].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna4_sensor4_offline",                 &antenna[4].temperature_sensor[4].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor4_calibrate_T",             &antenna[4].temperature_sensor[4].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna4_sensor4_rtx_power_autoadjust",    &antenna[4].temperature_sensor[4].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna4_sensor4_tx_attenuator",           &antenna[4].temperature_sensor[4].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor4_rx_attenuator"    ,       &antenna[4].temperature_sensor[4].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor4_start_freq_tab_index",    &antenna[4].temperature_sensor[4].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor4_end_freq_tab_index",      &antenna[4].temperature_sensor[4].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor4_slope_T",                 &antenna[4].temperature_sensor[4].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna4_sensor5_offline",                 &antenna[4].temperature_sensor[5].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor5_calibrate_T",             &antenna[4].temperature_sensor[5].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna4_sensor5_rtx_power_autoadjust",    &antenna[4].temperature_sensor[5].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna4_sensor5_tx_attenuator",           &antenna[4].temperature_sensor[5].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor5_rx_attenuator"    ,       &antenna[4].temperature_sensor[5].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna4_sensor5_start_freq_tab_index",    &antenna[4].temperature_sensor[5].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor5_end_freq_tab_index",      &antenna[4].temperature_sensor[5].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna4_sensor5_slope_T",                 &antenna[4].temperature_sensor[5].measure_slope,                SIGNAL_DATA_TYPE_l},

    {"antenna5_saw_delay_from_tx",               &antenna[5].delay_time_from_tx_to_rx,                           SIGNAL_DATA_TYPE_ui},
    {"antenna5_saw_send_hold_time",              &antenna[5].send_hold_time,                                     SIGNAL_DATA_TYPE_ul},
    {"antenna5_sensor0_offline",                 &antenna[5].temperature_sensor[0].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor0_calibrate_T",             &antenna[5].temperature_sensor[0].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna5_sensor0_rtx_power_autoadjust",    &antenna[5].temperature_sensor[0].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna5_sensor0_tx_attenuator",           &antenna[5].temperature_sensor[0].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor0_rx_attenuator"    ,       &antenna[5].temperature_sensor[0].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor0_start_freq_tab_index",    &antenna[5].temperature_sensor[0].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor0_end_freq_tab_index",      &antenna[5].temperature_sensor[0].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor0_slope_T",                 &antenna[5].temperature_sensor[0].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna5_sensor1_offline",                 &antenna[5].temperature_sensor[1].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor1_calibrate_T",             &antenna[5].temperature_sensor[1].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna5_sensor1_rtx_power_autoadjust",    &antenna[5].temperature_sensor[1].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna5_sensor1_tx_attenuator",           &antenna[5].temperature_sensor[1].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor1_rx_attenuator"    ,       &antenna[5].temperature_sensor[1].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor1_start_freq_tab_index",    &antenna[5].temperature_sensor[1].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor1_end_freq_tab_index",      &antenna[5].temperature_sensor[1].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor1_slope_T",                 &antenna[5].temperature_sensor[1].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna5_sensor2_offline",                 &antenna[5].temperature_sensor[2].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor2_calibrate_T",             &antenna[5].temperature_sensor[2].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna5_sensor2_rtx_power_autoadjust",    &antenna[5].temperature_sensor[2].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna5_sensor2_tx_attenuator",           &antenna[5].temperature_sensor[2].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor2_rx_attenuator"    ,       &antenna[5].temperature_sensor[2].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor2_start_freq_tab_index",    &antenna[5].temperature_sensor[2].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor2_end_freq_tab_index",      &antenna[5].temperature_sensor[2].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor2_slope_T",                 &antenna[5].temperature_sensor[2].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna5_sensor3_offline",                 &antenna[5].temperature_sensor[3].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor3_calibrate_T",             &antenna[5].temperature_sensor[3].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna5_sensor3_rtx_power_autoadjust",    &antenna[5].temperature_sensor[3].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna5_sensor3_tx_attenuator",           &antenna[5].temperature_sensor[3].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor3_rx_attenuator"    ,       &antenna[5].temperature_sensor[3].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor3_start_freq_tab_index",    &antenna[5].temperature_sensor[3].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor3_end_freq_tab_index",      &antenna[5].temperature_sensor[3].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor3_slope_T",                 &antenna[5].temperature_sensor[3].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna5_sensor4_offline",                 &antenna[5].temperature_sensor[4].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor4_calibrate_T",             &antenna[5].temperature_sensor[4].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna5_sensor4_rtx_power_autoadjust",    &antenna[5].temperature_sensor[4].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna5_sensor4_tx_attenuator",           &antenna[5].temperature_sensor[4].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor4_rx_attenuator"    ,       &antenna[5].temperature_sensor[4].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor4_start_freq_tab_index",    &antenna[5].temperature_sensor[4].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor4_end_freq_tab_index",      &antenna[5].temperature_sensor[4].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor4_slope_T",                 &antenna[5].temperature_sensor[4].measure_slope,                SIGNAL_DATA_TYPE_l},
    {"antenna5_sensor5_offline",                 &antenna[5].temperature_sensor[5].offline,                      SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor5_calibrate_T",             &antenna[5].temperature_sensor[5].calibrate_temperature_set,    SIGNAL_DATA_TYPE_i},
    {"antenna5_sensor5_rtx_power_autoadjust",    &antenna[5].temperature_sensor[5].rtx_power_autoadjust_enable,  SIGNAL_DATA_TYPE_c},
    {"antenna5_sensor5_tx_attenuator",           &antenna[5].temperature_sensor[5].tx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor5_rx_attenuator"    ,       &antenna[5].temperature_sensor[5].rx_attenuator_set,            SIGNAL_DATA_TYPE_uc},
    {"antenna5_sensor5_start_freq_tab_index",    &antenna[5].temperature_sensor[5].start_freq_tab_index,         SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor5_end_freq_tab_index",      &antenna[5].temperature_sensor[5].end_freq_tab_index,           SIGNAL_DATA_TYPE_ui},
    {"antenna5_sensor5_slope_T",                 &antenna[5].temperature_sensor[5].measure_slope,                SIGNAL_DATA_TYPE_l},

};

int32 const setting_system_define_num = sizeof(setting_system_define) / sizeof(setting_system_define[0]);

